### ISSUE TITLE
How can I add new environment variable for FrontEnd con local?

### ISSUE THREAD

**Issue by remy727** [Shopify/shopify-app-template-ruby#118]
```yml
# heroku.yml
build:
  docker:
    web: Dockerfile.web
    worker: Dockerfile.worker
  config:
    SHOPIFY_API_KEY: API_KEY
    KEY: VALUE
```

```js
# frontend/vite.config.js
// rest of the code

export default defineConfig({
  root: dirname(fileURLToPath(import.meta.url)),
  plugins: [react()],
  define: {
    "process.env.SHOPIFY_API_KEY": JSON.stringify(process.env.SHOPIFY_API_KEY),
    "process.env.KEY": JSON.stringify(process.env.KEY),
  },
 // rest config
});
```

This works on production. But how can I add `KEY` env on local?
